# Generated by Django 3.2.25 on 2024-10-22 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_users_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='users',
            name='name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(max_length=250),
        ),
    ]
